Fix VCS extension point attribute to use vcsClass instead of implementation
Changed the VCS extension point from using 'implementation' to 'vcsClass' attribute.
This fixes the NullPointerException that occurred when opening plugin settings.

The error was:
java.lang.NullPointerException: Parameter specified as non-null is null:
method com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass, parameter className
at com.intellij.openapi.vcs.impl.VcsEP.createVcs(VcsEP.java:38)

The VCS extension point in IntelliJ Platform uses a bean class (VcsEP) that expects
the 'vcsClass' attribute to specify the VCS implementation class, not 'implementation'.

Changed:
- <vcs implementation="net.chikach.intellijjj.JujutsuVcs" ...>
+ <vcs vcsClass="net.chikach.intellijjj.JujutsuVcs" ...>

Co-authored-by: chika3742 <43089218+chika3742@users.noreply.github.com>